name: Deploy Go Server

on:
  push:
    branches:
      - master # Trigger deployment on push to the master branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.23" # Specify your Go version

      - name: Build Go application
        run: go build -o go-demo-server main.go # Compile the Go app

      - name: Test application
        run: go test ./...
      
      
      - name: Sync to Server with rsync
        uses: appleboy/scp-action@v0.1.6
        with:
          host: ${{ vars.SERVER_IP }}
          username: ${{ vars.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "go-demo-server" # Source binary
          target: "/home/ubuntu/ci_cd_demo" # Destination on server

      - name: Restart service
        run: |
          echo '${{ secrets.SSH_PRIVATE_KEY }}' >> ssh_id
          chmod 600 ssh_id
          ssh -o StrictHostKeyChecking=no -i ssh_id ${{ vars.SERVER_USER }}@${{ vars.SERVER_IP }} 'sudo systemctl restart go-demo-server'
